// svelte/src/components/CForm.svelte
<script lang="ts">
  import {
    validateFields,
    type ValidationField,
    validationFieldsKey,
    validationStateKey,
  } from "@common/ts/validation/validateFields";
  import { setContext } from "svelte";
  import { writable } from "svelte/store";

  let _class: string = "";
  export { _class as class };

  export let submit: (reset: () => void) => void;

  let submitTried = writable(false);
  let isInvalid = writable(false);

  let fields: ValidationField[] = [];

  const validate = async () => {
    const isValid = await validateFields(fields);

    isInvalid.set(!isValid);

    return isValid;
  };

  setContext(validationFieldsKey, {
    register: (field: ValidationField) => {
      fields = [...fields, field];
    },
    revalidate: validate,
  });

  setContext(validationStateKey, { submitTried, isInvalid });

  const submitForm = async (event: Event) => {
    submitTried.set(true);

    const isValid = await validate();
    if (!isValid) return;

    submit(() => {
      submitTried.set(false);
      isInvalid.set(false);
    });
  };
</script>

<form on:submit|preventDefault={submitForm} novalidate class={_class}>
  <slot />
</form>

// vue/src/components/CForm.vue
<script setup lang="ts">
import {
  validateFields,
  ValidationField,
  validationFieldsKey,
  validationStateKey,
} from "@common/ts/validation/validateFields";
import { ref, provide } from "vue";

const props = defineProps<{ submit: (reset: () => void) => void }>();

const submitTried = ref(false);
const isInvalid = ref(false);

const fields = ref<ValidationField[]>([]);

const validate = async () => {
  const isValid = await validateFields(fields.value);

  isInvalid.value = !isValid;

  return isValid;
};

provide(validationFieldsKey, {
  register: (field: ValidationField) => {
    fields.value.push(field);
  },
  revalidate: validate,
});

provide(validationStateKey, { submitTried, isInvalid });

const submitForm = async (event: Event) => {
  submitTried.value = true;

  const isValid = await validate();
  if (!isValid) return;

  props.submit(() => {
    submitTried.value = false;
    isInvalid.value = false;
  });
};
</script>

<template>
  <form @submit.prevent="submitForm" novalidate>
    <slot />
  </form>
</template>
