// vue/src/components/CAppLayout.vue
<script setup lang="ts">
import { useStore } from "@/utils/store";
import { logout } from "@common/ts/api/logout";
import CButton from "./CButton.vue";
import CMainMenu from "./CMainMenu.vue";
import { useRouter } from "vue-router";

const store = useStore();
const router = useRouter();

const doLogout = () => {
  logout();
  store.isLoggedIn.value = false;
  router.push({ name: "login" });
};

const links = [
  { href: import.meta.env.VITE_BACKEND_URL, name: "Backend" },
  { href: import.meta.env.VITE_VUE_APP_URL, name: "Vue", current: true },
  { href: import.meta.env.VITE_SOLID_APP_URL, name: "Solid JS" },
  { href: import.meta.env.VITE_SVELTE_APP_URL, name: "Svelte" },
];
</script>

<template>
  <div class="app-layout">
    <div class="app-layout-header">
      <h1 class="app-layout-header-app-name">Thessenger</h1>

      {{ store.userName.value }}

      <c-button class="app-layout-header-sign-out" @click="doLogout">
        Odhlásit se
      </c-button>
    </div>
    <div class="app-layout-sidebar">
      <c-main-menu />
    </div>
    <div class="app-layout-content">
      <router-view></router-view>
    </div>
    <div class="app-layout-footer">
      <div class="app-layout-footer-links">
        <template v-for="link in links">
          <span v-if="link.current" class="current-app">
            {{ link.name }}
          </span>
          <a v-else :href="link.href" target="_blank" class="link">
            {{ link.name }}
          </a>
        </template>
      </div>
      <span class="app-layout-footer-footnote">
        Diplomová práce Davida Hrůzy
      </span>
    </div>
  </div>
</template>

<style scoped></style>

// solidjs/src/components/CAppLayout.tsx

import { useStore } from "@/utils/store";
import { logout } from "@common/ts/api/logout";
import CButton from "./CButton";
import CMainMenu from "./CMainMenu";
import { Component, For, JSX, Show } from "solid-js";
import { useNavigate } from "@solidjs/router";

export const CAppLayout: Component<{
  children: JSX.Element,
}> = (props) => {
  const store = useStore();
  const navigate = useNavigate();

  if (!store.isLoggedIn()) {
    navigate('/');
  }

  const doLogout = () => {
    logout();
    store.setIsLoggedIn(false);
    navigate('/');
  };

  const links = [
    { href: import.meta.env.VITE_BACKEND_URL, name: "Backend" },
    { href: import.meta.env.VITE_VUE_APP_URL, name: "Vue" },
    { href: import.meta.env.VITE_SOLID_APP_URL, name: "Solid JS", current: true },
    { href: import.meta.env.VITE_SVELTE_APP_URL, name: "Svelte" },
  ];

  return (
    <div class="app-layout">
      <div class="app-layout-header">
        <h1 class="app-layout-header-app-name">Thessenger</h1>

        {store.userName()}

        <CButton class="app-layout-header-sign-out" onClick={doLogout}>
          Odhlásit se
        </CButton>
      </div>
      <div class="app-layout-sidebar">
        <CMainMenu />
      </div>
      <div class="app-layout-content">
        {props.children}
      </div>
      <div class="app-layout-footer">
        <div class="app-layout-footer-links">
          <For each={links}>
            {(link) => <>
              <Show when={link.current}>
                <span class="current-app">
                  {link.name}
                </span>
              </Show>
              <Show when={!link.current}>
                <a href={link.href} target="_blank" class="link">
                  {link.name}
                </a>
              </Show>
            </>
            }
          </For>
        </div>
        <span class="app-layout-footer-footnote">
          Diplomová práce Davida Hrůzy
        </span>
      </div>
    </div>
  )
}

export default CAppLayout;
