// vue/src/components/CButton.vue
<script setup lang="ts">
import { validationStateKey } from "@common/ts/validation/validateFields";
import { useButtonConfirmation } from "@common/ts/api/buttonConfirmation";
import { inject, computed, Ref, ref } from "vue";

const props = defineProps<{
  color?: "primary" | "secondary" | "success" | "error";
  size?: "small" | "medium" | "large";
  loading?: boolean;
  disabled?: boolean;
  confirm?: boolean;
  onClick?: () => void;
}>();

const validationStatus = inject<
  | {
      submitTried: Ref<boolean>;
      isInvalid: Ref<boolean>;
    }
  | undefined
>(validationStateKey, undefined);

const currentColor = computed(() => {
  if (validationStatus?.isInvalid.value) return "error";
  if (validationStatus?.submitTried.value) return "success";

  return props.color;
});

const shouldConfirm = ref(false);
const { setShouldConfirmTimeout, clearShouldConfirmTimeout } =
  useButtonConfirmation(() => (shouldConfirm.value = false));

const onClick = () => {
  if (props.disabled) return;
  if (!props.onClick) return;

  if (props.confirm && !shouldConfirm.value) {
    shouldConfirm.value = true;
    return;
  }
  clearShouldConfirmTimeout();
  shouldConfirm.value = false;

  props.onClick();
};
</script>

<template>
  <button
    v-bind="$attrs"
    class="button"
    :class="{
      button__disabled: disabled,
      [`button__${currentColor}`]: currentColor,
      [`button__${size}`]: size,
      [`button__confirm`]: shouldConfirm,
    }"
    @click="onClick"
    @mouseover="clearShouldConfirmTimeout"
    @mouseout="setShouldConfirmTimeout"
  >
    <slot :shouldConfirm="shouldConfirm" />

    <span v-if="loading" class="loader button-loader" />
  </button>
</template>

// solidjs/src/components/CButton.tsx
import { Accessor, Component, createSignal, JSX, Show } from "solid-js";
import { useButtonConfirmation } from "@common/ts/api/buttonConfirmation";
import { useValidation } from "./CForm";

export const CButton: Component<{
  children: JSX.Element | ((shouldConfirm: Accessor<boolean>) => JSX.Element),
  class?: string;
  color?: "primary" | "secondary" | "success" | "error";
  size?: "small" | "medium" | "large";
  loading?: boolean;
  disabled?: boolean;
  confirm?: boolean;
  onClick?: () => void;
  shouldConfirm?: string;
}> = (props) => {
  const validationStatus = useValidation();

  const currentColor = () => {
    if (validationStatus?.isInvalid()) return "error";
    if (validationStatus?.submitTried()) return "success";

    return props.color;
  };

  const [shouldConfirm, setShouldConfirm] = createSignal(false);
  const { setShouldConfirmTimeout, clearShouldConfirmTimeout } =
    useButtonConfirmation(() => setShouldConfirm(false));

  const onClick = () => {
    if (props.disabled) return;
    if (!props.onClick) return;

    if (props.confirm && !shouldConfirm()) {
      setShouldConfirm(true);
      return;
    }
    clearShouldConfirmTimeout();
    setShouldConfirm(false);

    props.onClick();
  };

  return (
    <button
      class={props.class}
      classList={{
        button: true,
        button__disabled: props.disabled,
        [`button__${currentColor()}`]: !!currentColor(),
        [`button__${props.size}`]: !!props.size,
        [`button__confirm`]: shouldConfirm(),
      }}
      onClick={onClick}
      onMouseOver={clearShouldConfirmTimeout}
      onMouseOut={setShouldConfirmTimeout}
    >
      <Show when={props.loading}>
        <span class="loader button-loader" />
      </Show>

      {typeof props.children === 'function' ? props.children(shouldConfirm) : props.children}
    </button>
  )
}

export default CButton;
