// svelte/src/components/CInputSelect.svelte
<script lang="ts">
  import type { SelectItem } from "@common/ts/api/select";
  import { getRequired } from "@common/ts/validation/required";
  import type { RuleType } from "@common/ts/validation/ruleType";
  import {
    type ValidationField,
    validationFieldsKey,
    validationStateKey,
  } from "@common/ts/validation/validateFields";
  import { onMount } from "svelte";
  import type { Writable } from "svelte/store";
  import { getContext, onDestroy } from "svelte";

  export let items: SelectItem[];
  export let name: string;
  export let label: string;
  export let state: "success" | "error" = null;
  export let required: boolean = false;
  export let disabled: boolean = false;
  export let value: (string | number)[] | string | number;
  export let rules: RuleType[] = [];
  export let multiple: boolean = false;

  let search = "";
  let element: HTMLInputElement | HTMLTextAreaElement;
  let innerValue: string | number | (string | number)[] = multiple
    ? value ?? []
    : value ?? "";
  let errorMessages: string[] = [];
  let isOpen: boolean = false;
  let hasFocus: boolean = false;

  const field: ValidationField = {
    getValue: () => innerValue,
    rules: (required ? [getRequired()] : []).concat(rules ?? []),
    setMessage: (messages) => (errorMessages = messages),
  };

  const registerField = getContext<{
    register: (field: ValidationField) => void;
    revalidate: () => void;
  }>(validationFieldsKey);
  registerField?.register(field);

  const validationStatus = getContext<
    | {
        submitTried: Writable<boolean>;
        isInvalid: Writable<boolean>;
      }
    | undefined
  >(validationStateKey);

  $: {
    if (value !== undefined) {
      innerValue = value;
    }
  }

  const updateInput = (event: Event) => {
    if (disabled) return;
    const target = event.target as HTMLInputElement;

    if (isOpen) {
      search = target.value;
    } else {
      value = target.value;
      innerValue = target.value;

      if (errorMessages.length) registerField?.revalidate();
    }
  };

  $: currentState = errorMessages.length
    ? "error"
    : validationStatus?.submitTried
    ? "success"
    : state;

  const isSelected = (item: SelectItem): boolean => {
    if (Array.isArray(innerValue)) {
      return innerValue.some((i) => i === item.value);
    }
    return innerValue === item.value;
  };

  const close = () => {
    isOpen = false;
    search = "";
  };

  const selectItem = (item: SelectItem) => {
    if (item.disabled) return;

    search = "";

    if (Array.isArray(innerValue)) {
      if (isSelected(item)) {
        innerValue = innerValue.filter((i) => i !== item.value);
      } else {
        innerValue = [...innerValue, item.value];
      }
    } else {
      innerValue = item.value;
      close();
    }

    value = innerValue;
  };

  const onClickEvent = (e: Event) => {
    if (e.target !== element) {
      close();
    }
  };
  const onKeydownEvent = (e: KeyboardEvent) => {
    if (e.key === "Escape") {
      close();
    }
  };

  onMount(() => {
    document.addEventListener("click", onClickEvent);
    document.addEventListener("keydown", onKeydownEvent);
  });
  onDestroy(() => {
    document.removeEventListener("click", onClickEvent);
    document.removeEventListener("keydown", onKeydownEvent);
  });

  const getLabel = (value: string | number) =>
    items.find((item) => item.value === value)?.label;

  $: formattedInnerValue = Array.isArray(innerValue)
    ? innerValue.map(getLabel).join(", ")
    : getLabel(innerValue);

  $: filteredItems = items.filter((item) => item.label.includes(search));

  const itemKeyDown = (e: KeyboardEvent, item: SelectItem, index: number) => {
    if (e.key === "Enter") {
      selectItem(item);
    }
    if (e.key === "Tab") {
      index === filteredItems.length - 1 ? (isOpen = false) : null;
    }
  };

  const closeOnShiftTab = (e: KeyboardEvent) => {
    if (e.shiftKey && e.key == "Tab") {
      isOpen = false;
    }
  };
</script>

<div
  class={`input-select-with-label ${
    currentState ? `input-select__state-${currentState}` : ""
  }`}
>
  {#if label}
    <label class="label">{label}</label>
  {/if}
  <input
    bind:this={element}
    value={isOpen && hasFocus ? search : formattedInnerValue}
    readonly={!isOpen}
    {name}
    class="input-select"
    class:has-focus={isOpen}
    {disabled}
    placeholder=" "
    autocomplete="off"
    on:input={updateInput}
    on:focus={() => (isOpen = true)}
    on:focusin={() => (hasFocus = true)}
    on:focusout={() => (hasFocus = false)}
    on:click={() => (isOpen = true)}
    on:keydown={closeOnShiftTab}
  />
  <div class="input-select-items" class:is-open={isOpen}>
    <ul>
      {#if filteredItems.length === 0}
        <li class="disabled" on:click|stopPropagation>Nic nenalezeno</li>
      {/if}
      {#each filteredItems as item, index}
        <li
          class:selected={isSelected(item)}
          class:disabled={item.disabled}
          tabindex={0}
          on:click|stopPropagation={() => selectItem(item)}
          on:keydown={(e) => itemKeyDown(e, item, index)}
        >
          {item.label}
        </li>
      {/each}
    </ul>
  </div>
  <ul class="input-select-messages">
    {#each errorMessages as errorMessage}
      <li>
        {errorMessage}
      </li>
    {/each}
  </ul>
</div>

// solidjs/src/components/CInputSelect.tsx

import { SelectItem } from "@common/ts/api/select";
import { getRequired } from "@common/ts/validation/required";
import { RuleType } from "@common/ts/validation/ruleType";
import { ValidationField } from "@common/ts/validation/validateFields";
import { Accessor, Component, For, Show, createEffect, createSignal, onCleanup, onMount } from "solid-js";
import { useValidation, useValidationFields } from "./CForm";

export const CInputSelect: Component<{
  items: SelectItem[];
  name?: string;
  label?: string;
  state?: "success" | "error";
  required?: boolean;
  disabled?: boolean;
  value?: (string | number)[] | string | number;
  updateValue?: (value: (string | number)[] | string | number) => void;
  rules?: RuleType[];
  multiple?: boolean;
}> = (props) => {

  const [search, setSearch] = createSignal("");
  const [element, setElement] = createSignal<HTMLInputElement | HTMLTextAreaElement>();
  const [innerValue, setInnerValue] = createSignal<string | number | (string | number)[]>(
    props.multiple ? props.value ?? [] : props.value ?? ""
  );
  const [errorMessages, setErrorMessages] = createSignal<string[]>([]);
  const [isOpen, setIsOpen] = createSignal<boolean>(false);
  const [hasFocus, setHasFocus] = createSignal<boolean>(false);

  const field: ValidationField = {
    getValue: innerValue,
    rules: (props.required ? [getRequired()] : []).concat(props.rules ?? []),
    setMessage: (messages) => (setErrorMessages([...messages])),
  };

  const registerField = useValidationFields();
  const validationStatus = useValidation();

  registerField?.register(field);

  createEffect(() => {
    if (props.value !== undefined) {
      setInnerValue(props.value);
    }
  }
  );

  const updateInput = (event: Event) => {
    if (props.disabled) return;
    const target = event.target as HTMLInputElement;

    if (isOpen()) {
      setSearch(target.value);
    } else {
      props.updateValue?.(target.value);
      setInnerValue(target.value);

      if (errorMessages().length) registerField?.revalidate();
    }
  };

  const currentState = () => {
    if (errorMessages().length) return "error";
    if (validationStatus?.submitTried()) return "success";

    return props.state;
  };

  const isSelected = (item: SelectItem): boolean => {
    const value = innerValue();
    if (Array.isArray(value)) {
      return value.some((i) => i === item.value);
    }
    return value === item.value;
  };

  const close = () => {
    setIsOpen(false);
    setSearch("");
  };

  const selectItem = (item: SelectItem) => {
    if (item.disabled) return;

    setSearch("");

    const value = innerValue();

    if (Array.isArray(value)) {
      if (isSelected(item)) {
        setInnerValue(value.filter((i) => i !== item.value));
      } else {
        setInnerValue(() => [item.value, ...value]);
      }
    } else {
      setInnerValue(item.value);
      close();
    }

    props.updateValue?.(innerValue());
  };

  const onClickEvent = (e: Event) => {
    if (e.target !== element()) {
      close();
    }
  };
  const onKeydownEvent = (e: KeyboardEvent) => {
    if (e.key === "Escape") {
      close();
    }
  };

  onMount(() => {
    document.addEventListener("click", onClickEvent);
    document.addEventListener("keydown", onKeydownEvent);
  });
  onCleanup(() => {
    document.removeEventListener("click", onClickEvent);
    document.removeEventListener("keydown", onKeydownEvent);
  });

  const formattedInnerValue = () => {
    const getLabel = (value: string | number) =>
      props.items.find((item) => item.value === value)?.label;
    const value = innerValue();

    return Array.isArray(value)
      ? value.map(getLabel).join(", ")
      : getLabel(value);
  };

  const filteredItems = () =>
    props.items.filter((item) => item.label.includes(search()));

  const itemKeyDown = (e: KeyboardEvent, item: SelectItem, index: Accessor<number>) => {
    if (e.key === 'Enter') {
      selectItem(item)
    }
    if (e.key === 'Tab') {
      index() === filteredItems().length - 1 ? (setIsOpen(false)) : null
    }
  }

  const closeOnShiftTab = (e: KeyboardEvent) => {
    if (e.shiftKey && e.key == 'Tab') {
      setIsOpen(false)
    }
  }

  return (
    <div
      class="input-select-with-label"
      classList={{
        [`input-select__state-${currentState()}`]: !!currentState(),
      }}
    >
      <label v-if="label" class="label">{props.label}</label>
      <input
        ref={setElement}
        value={isOpen() && hasFocus() ? search() : formattedInnerValue()}
        readonly={!isOpen()}
        name={props.name}
        class="input-select"
        classList={{ 'has-focus': isOpen() }}
        disabled={props.disabled}
        placeholder=" "
        autocomplete="off"
        onInput={updateInput}
        onFocus={() => setIsOpen(true)}
        onFocusIn={() => setHasFocus(true)}
        onFocusOut={() => setHasFocus(false)}
        onClick={() => setIsOpen(true)}
        onKeyDown={closeOnShiftTab}
      />
      <div class="input-select-items" classList={{ 'is-open': isOpen() }}>
        <ul>
          <Show
            when={filteredItems().length !== 0}
            fallback={
              <li class="disabled" onClick={(e) => e.stopPropagation()}>
                Nic nenalezeno
              </li>
            }>
            <For each={filteredItems()}>
              {(item, index) => <li
                classList={{ selected: isSelected(item), disabled: item.disabled }}
                tabindex="0"
                onClick={(e) => { selectItem(item); e.stopPropagation() }}
                onKeyDown={(e) => itemKeyDown(e, item, index)}
              >
                {item.label}
              </li>}
            </For>
          </Show>

        </ul>
      </div>
      <ul class="input-select-messages">
        <For each={errorMessages()}>
          {(errorMessage) => <li>{errorMessage}</li>}
        </For>
      </ul>
    </div>
  )
}

export default CInputSelect;
