// vue/src/components/CMessageList.vue
<script lang="ts" setup>
import CButton from "./CButton.vue";
import CLink from "./CLink.vue";
import { formatApiDateString } from "@common/ts/api/date";
import { Message, MessageType } from "@common/ts/api/message";
import { deleteMessage } from "@common/ts/api/deleteMessage";
import { withLoading } from "@/utils/loadingState";
import { defineComponent, h } from "vue";

const props = defineProps<{
  messages: Message[];
  showUser: (message: Message) => string;
  onDeleted?: (messageId: string | number) => void;
}>();

const createContentPreview = (content: string) =>
  content.length > 100 ? content.slice(0, 100) + " ..." : content;

const deleteButton = defineComponent({
  props: {
    messageId: {
      type: [Number, String],
      required: true,
    },
  },

  setup(innerProps) {
    const { loading, run: deleteMessageOnClick } = withLoading(
      deleteMessage,
      () => props.onDeleted?.(innerProps.messageId)
    );

    return () =>
      h(
        CButton,
        {
          size: "medium",
          color: "error",
          disabled: loading.value,
          loading: loading.value,
          confirm: true,
          onClick: () => deleteMessageOnClick(innerProps.messageId),
        },
        {
          default: ({ shouldConfirm }: { shouldConfirm: boolean }) =>
            shouldConfirm ? "Opravdu?" : "Smazat",
        }
      );
  },
});
</script>

<template>
  <ul>
    <li v-for="message in messages" class="message-list-item">
      <span class="message-list-item-user">
        <span
          v-if="!message.seen_at && message.type === MessageType.TYPE_RECEIVED"
          class="menu-badge list-variant"
        >
        </span>
        {{ showUser(message) }}
      </span>
      <span class="message-list-item-date">
        {{ formatApiDateString(message.created_at) }}
      </span>
      <span class="message-list-item-subject {">
        {{ message.message_content?.subject }}
      </span>
      <span class="message-list-item-content">
        {{ createContentPreview(message.message_content?.content ?? "") }}
      </span>
      <span class="message-list-item-action">
        <slot name="actions" :message="message" />
        <c-link
          :to="{ name: 'messageDetail', params: { messageId: message.id } }"
        >
          <c-button size="medium"> Zobrazit </c-button>
        </c-link>
        <delete-button :message-id="message.id" />
      </span>
    </li>
  </ul>
</template>

// solidjs/src/components/CMessageList.tsx

import CButton from "./CButton";
import CLink from "./CLink";
import { formatApiDateString } from "@common/ts/api/date";
import { Message } from "@common/ts/api/message";
import { deleteMessage } from "@common/ts/api/deleteMessage";
import { withLoading } from "@/utils/loadingState";
import { Component, For, JSX } from "solid-js";

const CMessageList: Component<{
  messages: Message[];
  showUser: (message: Message) => string;
  onDeleted?: (messageId: string | number) => void;
  actions?: (message: Message) => JSX.Element
}> = (props) => {

  const createContentPreview = (content: string) =>
    content.length > 100 ? content.slice(0, 100) + " ..." : content;

  const DeleteButton: Component<{
    messageId: number | string,
  }> = (innerProps) => {
    const { loading, run: deleteMessageOnClick } = withLoading(
      deleteMessage,
      () => props.onDeleted?.(innerProps.messageId)
    );

    return (
      <CButton
        size="medium"
        color="error"
        disabled={loading()}
        loading={loading()}
        confirm
        onClick={() => deleteMessageOnClick(innerProps.messageId)}
        children={(shouldConfirm) => shouldConfirm() ? "Opravdu?" : "Smazat"}
      />
    )
  }

  return (

    <ul>
      <For each={props.messages}>
        {(message) => <li class="message-list-item">
          <span class="message-list-item-user">
            <span
              v-if="!message.seen_at && message.type === MessageType.TYPE_RECEIVED"
              class="menu-badge list-variant"
            >
            </span>
            {props.showUser(message)}
          </span>
          <span class="message-list-item-date">
            {formatApiDateString(message.created_at)}
          </span>
          <span class="message-list-item-subject {">
            {message.message_content?.subject}
          </span>
          <span class="message-list-item-content">
            {createContentPreview(message.message_content?.content ?? "")}
          </span>
          <span class="message-list-item-action">
            {props.actions?.(message)}
            <CLink
              to={`/message/${message.id}/detail`}
            >
              <CButton size="medium"> Zobrazit </CButton>
            </CLink>
            <DeleteButton messageId={message.id} />
          </span>
        </li>
        }
      </For>
    </ul >
  )
}

export default CMessageList;
