// svelte/src/components/CMessages.svelte
<script lang="ts">
  import { hideMessage, messageQueue } from "@/utils/messages";
  import CCard from "./CCard.svelte";
  import CPortal from "./CPortal.svelte";

  export const title: string = "";
</script>

<CPortal>
  <section class="message-area">
    {#each $messageQueue as message, index}
      <CCard
        title={message.title}
        color={message.type}
        class="message"
        closable
        on:close={() => hideMessage(index)}
      >
        {message.content}
      </CCard>
    {/each}
  </section>
</CPortal>

// solidjs/src/components/CMessages.tsx
import { hideMessage, messageQueue } from "@/utils/messages";
import CCard from "./CCard";
import { For, Portal } from "solid-js/web";
import { Component } from "solid-js";

const CMessages: Component = () => {

  return (
    <Portal mount={document.body}>
      <section class="message-area">
        <For each={messageQueue()}>
          {(message, index) =>
            <CCard
              title={message.title}
              color={message.type}
              class="message"
              closable
              close={() => hideMessage(index())}
            >
              {message.content}
            </CCard>
          }
        </For>
      </section>
    </Portal>
  )
}

export default CMessages;
