// vue/src/components/CButton.vue
<script setup lang="ts">
import { validationStateKey } from "@common/ts/validation/validateFields";
import { useButtonConfirmation } from "@common/ts/api/buttonConfirmation";
import { inject, computed, Ref, ref } from "vue";

const props = defineProps<{
  color?: "primary" | "secondary" | "success" | "error";
  size?: "small" | "medium" | "large";
  loading?: boolean;
  disabled?: boolean;
  confirm?: boolean;
  onClick?: () => void;
}>();

const validationStatus = inject<
  | {
      submitTried: Ref<boolean>;
      isInvalid: Ref<boolean>;
    }
  | undefined
>(validationStateKey, undefined);

const currentColor = computed(() => {
  if (validationStatus?.isInvalid.value) return "error";
  if (validationStatus?.submitTried.value) return "success";

  return props.color;
});

const shouldConfirm = ref(false);
const { setShouldConfirmTimeout, clearShouldConfirmTimeout } =
  useButtonConfirmation(() => (shouldConfirm.value = false));

const onClick = () => {
  if (props.disabled) return;
  if (!props.onClick) return;

  if (props.confirm && !shouldConfirm.value) {
    shouldConfirm.value = true;
    return;
  }
  clearShouldConfirmTimeout();
  shouldConfirm.value = false;

  props.onClick();
};
</script>

<template>
  <button
    v-bind="$attrs"
    class="button"
    :class="{
      button__disabled: disabled,
      [`button__${currentColor}`]: currentColor,
      [`button__${size}`]: size,
      [`button__confirm`]: shouldConfirm,
    }"
    @click="onClick"
    @mouseover="clearShouldConfirmTimeout"
    @mouseout="setShouldConfirmTimeout"
  >
    <slot :shouldConfirm="shouldConfirm" />

    <span v-if="loading" class="loader button-loader" />
  </button>
</template>

// svelte/src/components/CButton.svelte
<script lang="ts">
  import { validationStateKey } from "@common/ts/validation/validateFields";
  import { useButtonConfirmation } from "@common/ts/api/buttonConfirmation";
  import { createEventDispatcher, getContext } from "svelte";
  import type { Writable } from "svelte/store";
  const dispatch = createEventDispatcher();

  let _class: string = "";
  export { _class as class };
  export let color: "primary" | "secondary" | "success" | "error" = null;
  export let size: "small" | "medium" | "large" = null;
  export let loading: boolean = false;
  export let disabled: boolean = false;
  export let confirm: boolean = false;
  export let onClick: () => void = () => {};

  const { isInvalid, submitTried } =
    getContext<
      | {
          submitTried: Writable<boolean>;
          isInvalid: Writable<boolean>;
        }
      | undefined
    >(validationStateKey) ?? {};

  $: currentColor = $isInvalid ? "error" : $submitTried ? "success" : color;

  let shouldConfirm = false;
  const { setShouldConfirmTimeout, clearShouldConfirmTimeout } =
    useButtonConfirmation(() => (shouldConfirm = false));

  const onButtonClick = () => {
    dispatch("click");
    if (disabled) return;
    if (!onClick) return;

    if (confirm && !shouldConfirm) {
      shouldConfirm = true;
      return;
    }
    clearShouldConfirmTimeout();
    shouldConfirm = false;

    onClick();
  };
</script>

<button
  class={`button ${disabled ? "button_disabled" : ""} ${
    shouldConfirm ? "button__confirm" : ""
  } ${currentColor ? `button__${currentColor}` : ""} ${
    size ? `button__${size}` : ""
  } ${_class}`}
  on:click={onButtonClick}
  on:mouseover={clearShouldConfirmTimeout}
  on:focus={clearShouldConfirmTimeout}
  on:mouseout={setShouldConfirmTimeout}
  on:blur={setShouldConfirmTimeout}
>
  <slot {shouldConfirm} />

  {#if loading}
    <span class="loader button-loader" />
  {/if}
</button>
