// solidjs/src/components/CCard.tsx

import { Component, JSX, Show } from "solid-js";
import CButton from "./CButton";

export const CCard: Component<{
  title?: string;
  closable?: boolean;
  class?: string;
  color?: "primary" | "secondary" | "success" | "error";

  header?: JSX.Element,
  children?: JSX.Element,

  close?: () => void
}> = (props) => {
  return (
    <section class={`card card__${props.color} ${props.class}`}>
      <Show when={props.header || props.title}>
        <header class="card-header">
          <h2 class="header">{props.title}</h2>

          <div class="card-header-toolbox">
            <Show when={props.closable}>
              <CButton
                size="small"
                color={props.color}
                onClick={() => { props.close?.() }}
              >
                X
              </CButton>
            </Show>
          </div>
        </header>
      </Show>
      {props.children}
    </section >
  )
}

export default CCard;

// svelte/src/components/CCard.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import CButton from "./CButton.svelte";
  const dispatch = createEventDispatcher();

  let _class: string = "";
  export { _class as class };
  export let title: string | null = null;
  export let closable: boolean = false;
  export let color: "primary" | "secondary" | "success" | "error" = "primary";
</script>

<section class={`card card__${color} ${_class}`}>
  {#if $$slots.header || title}
    <header class="card-header">
      <slot name="header">
        <h2 class="header">{title}</h2>
      </slot>

      <div class="card-header-toolbox">
        {#if closable}
          <CButton size="small" {color} on:click={() => dispatch("close")}>
            X
          </CButton>
        {/if}
      </div>
    </header>
  {/if}
  <slot />
</section>
