// vue/src/components/CInputSelect.vue
<script setup lang="ts">
import { SelectItem } from "@common/ts/api/select";
import { getRequired } from "@common/ts/validation/required";
import { RuleType } from "@common/ts/validation/ruleType";
import {
  ValidationField,
  validationFieldsKey,
  validationStateKey,
} from "@common/ts/validation/validateFields";
import { inject, watch, ref, computed, Ref, onMounted, onUnmounted } from "vue";

const props = defineProps<{
  items: SelectItem[];
  name?: string;
  label?: string;
  state?: "success" | "error";
  required?: boolean;
  disabled?: boolean;
  value?: (string | number)[] | string | number;
  rules?: RuleType[];
  multiple?: boolean;
}>();

const emits = defineEmits<{
  (e: "update:value", value: string): void;
}>();

const search = ref("");
const element = ref<HTMLInputElement | HTMLTextAreaElement>();
const innerValue = ref<string | number | (string | number)[]>(
  props.multiple ? props.value ?? [] : props.value ?? ""
);
const errorMessages = ref<string[]>([]);
const isOpen = ref<boolean>(false);
const hasFocus = ref<boolean>(false);

const field: ValidationField = {
  getValue: () => innerValue.value,
  rules: (props.required ? [getRequired()] : []).concat(props.rules ?? []),
  setMessage: (messages) => (errorMessages.value = messages),
};

const registerField = inject<{
  register: (field: ValidationField) => void;
  revalidate: () => void;
}>(validationFieldsKey);
registerField?.register(field);

const validationStatus = inject<
  | {
      submitTried: Ref<boolean>;
      isInvalid: Ref<boolean>;
    }
  | undefined
>(validationStateKey, undefined);

watch(
  () => props.value,
  (value) => {
    if (value !== undefined) {
      innerValue.value = value;
    }
  }
);

const updateInput = (event: Event) => {
  if (props.disabled) return;
  const target = event.target as HTMLInputElement;

  if (isOpen.value) {
    search.value = target.value;
  } else {
    emits("update:value", target.value);
    innerValue.value = target.value;

    if (errorMessages.value.length) registerField?.revalidate();
  }
};

const currentState = computed(() => {
  if (errorMessages.value.length) return "error";
  if (validationStatus?.submitTried?.value) return "success";

  return props.state;
});

const isSelected = (item: SelectItem): boolean => {
  if (Array.isArray(innerValue.value)) {
    return innerValue.value.some((i) => i === item.value);
  }
  return innerValue.value === item.value;
};

const close = () => {
  isOpen.value = false;
  search.value = "";
};

const selectItem = (item: SelectItem) => {
  if (item.disabled) return;

  search.value = "";

  if (Array.isArray(innerValue.value)) {
    if (isSelected(item)) {
      innerValue.value = innerValue.value.filter((i) => i !== item.value);
    } else {
      innerValue.value.push(item.value);
    }
  } else {
    innerValue.value = item.value;
    close();
  }
};

const onClickEvent = (e: Event) => {
  if (e.target !== element.value) {
    close();
  }
};
const onKeydownEvent = (e: KeyboardEvent) => {
  if (e.key === "Escape") {
    close();
  }
};

onMounted(() => {
  document.addEventListener("click", onClickEvent);
  document.addEventListener("keydown", onKeydownEvent);
});
onUnmounted(() => {
  document.removeEventListener("click", onClickEvent);
  document.removeEventListener("keydown", onKeydownEvent);
});

const formattedInnerValue = computed(() => {
  const getLabel = (value: string | number) =>
    props.items.find((item) => item.value === value)?.label;

  return Array.isArray(innerValue.value)
    ? innerValue.value.map(getLabel).join(", ")
    : getLabel(innerValue.value);
});

const filteredItems = computed(() =>
  props.items.filter((item) => item.label.includes(search.value))
);
</script>

<template>
  <div
    class="input-select-with-label"
    :class="{
      [`input-select__state-${currentState}`]: currentState,
    }"
  >
    <label v-if="label" class="label">{{ label }}</label>
    <input
      ref="element"
      v-bind="$attrs"
      :value="isOpen && hasFocus ? search : formattedInnerValue"
      :readonly="!isOpen"
      :name="name"
      class="input-select"
      :class="{ 'has-focus': isOpen }"
      :disabled="disabled"
      placeholder=" "
      autocomplete="off"
      @input="updateInput"
      @focus="isOpen = true"
      @focusin="hasFocus = true"
      @focusout="hasFocus = false"
      @click="isOpen = true"
      @keydown.shift.tab="isOpen = false"
    />
    <div class="input-select-items" :class="{ 'is-open': isOpen }">
      <ul>
        <li v-if="filteredItems.length === 0" class="disabled" @click.stop>
          Nic nenalezeno
        </li>
        <li
          v-for="(item, index) in filteredItems"
          :class="{ selected: isSelected(item), disabled: item.disabled }"
          :tabindex="0"
          @click.stop="selectItem(item)"
          @keydown.enter="selectItem(item)"
          @keydown.tab="
            index === filteredItems.length - 1 ? (isOpen = false) : null
          "
        >
          {{ item.label }}
        </li>
      </ul>
    </div>
    <ul class="input-select-messages">
      <li v-for="errorMessage in errorMessages">
        {{ errorMessage }}
      </li>
    </ul>
  </div>
</template>

// svelte/src/components/CInputSelect.svelte
<script lang="ts">
  import type { SelectItem } from "@common/ts/api/select";
  import { getRequired } from "@common/ts/validation/required";
  import type { RuleType } from "@common/ts/validation/ruleType";
  import {
    type ValidationField,
    validationFieldsKey,
    validationStateKey,
  } from "@common/ts/validation/validateFields";
  import { onMount } from "svelte";
  import type { Writable } from "svelte/store";
  import { getContext, onDestroy } from "svelte";

  export let items: SelectItem[];
  export let name: string;
  export let label: string;
  export let state: "success" | "error" = null;
  export let required: boolean = false;
  export let disabled: boolean = false;
  export let value: (string | number)[] | string | number;
  export let rules: RuleType[] = [];
  export let multiple: boolean = false;

  let search = "";
  let element: HTMLInputElement | HTMLTextAreaElement;
  let innerValue: string | number | (string | number)[] = multiple
    ? value ?? []
    : value ?? "";
  let errorMessages: string[] = [];
  let isOpen: boolean = false;
  let hasFocus: boolean = false;

  const field: ValidationField = {
    getValue: () => innerValue,
    rules: (required ? [getRequired()] : []).concat(rules ?? []),
    setMessage: (messages) => (errorMessages = messages),
  };

  const registerField = getContext<{
    register: (field: ValidationField) => void;
    revalidate: () => void;
  }>(validationFieldsKey);
  registerField?.register(field);

  const validationStatus = getContext<
    | {
        submitTried: Writable<boolean>;
        isInvalid: Writable<boolean>;
      }
    | undefined
  >(validationStateKey);

  $: {
    if (value !== undefined) {
      innerValue = value;
    }
  }

  const updateInput = (event: Event) => {
    if (disabled) return;
    const target = event.target as HTMLInputElement;

    if (isOpen) {
      search = target.value;
    } else {
      value = target.value;
      innerValue = target.value;

      if (errorMessages.length) registerField?.revalidate();
    }
  };

  $: currentState = errorMessages.length
    ? "error"
    : validationStatus?.submitTried
    ? "success"
    : state;

  const isSelected = (item: SelectItem): boolean => {
    if (Array.isArray(innerValue)) {
      return innerValue.some((i) => i === item.value);
    }
    return innerValue === item.value;
  };

  const close = () => {
    isOpen = false;
    search = "";
  };

  const selectItem = (item: SelectItem) => {
    if (item.disabled) return;

    search = "";

    if (Array.isArray(innerValue)) {
      if (isSelected(item)) {
        innerValue = innerValue.filter((i) => i !== item.value);
      } else {
        innerValue = [...innerValue, item.value];
      }
    } else {
      innerValue = item.value;
      close();
    }

    value = innerValue;
  };

  const onClickEvent = (e: Event) => {
    if (e.target !== element) {
      close();
    }
  };
  const onKeydownEvent = (e: KeyboardEvent) => {
    if (e.key === "Escape") {
      close();
    }
  };

  onMount(() => {
    document.addEventListener("click", onClickEvent);
    document.addEventListener("keydown", onKeydownEvent);
  });
  onDestroy(() => {
    document.removeEventListener("click", onClickEvent);
    document.removeEventListener("keydown", onKeydownEvent);
  });

  const getLabel = (value: string | number) =>
    items.find((item) => item.value === value)?.label;

  $: formattedInnerValue = Array.isArray(innerValue)
    ? innerValue.map(getLabel).join(", ")
    : getLabel(innerValue);

  $: filteredItems = items.filter((item) => item.label.includes(search));

  const itemKeyDown = (e: KeyboardEvent, item: SelectItem, index: number) => {
    if (e.key === "Enter") {
      selectItem(item);
    }
    if (e.key === "Tab") {
      index === filteredItems.length - 1 ? (isOpen = false) : null;
    }
  };

  const closeOnShiftTab = (e: KeyboardEvent) => {
    if (e.shiftKey && e.key == "Tab") {
      isOpen = false;
    }
  };
</script>

<div
  class={`input-select-with-label ${
    currentState ? `input-select__state-${currentState}` : ""
  }`}
>
  {#if label}
    <label class="label">{label}</label>
  {/if}
  <input
    bind:this={element}
    value={isOpen && hasFocus ? search : formattedInnerValue}
    readonly={!isOpen}
    {name}
    class="input-select"
    class:has-focus={isOpen}
    {disabled}
    placeholder=" "
    autocomplete="off"
    on:input={updateInput}
    on:focus={() => (isOpen = true)}
    on:focusin={() => (hasFocus = true)}
    on:focusout={() => (hasFocus = false)}
    on:click={() => (isOpen = true)}
    on:keydown={closeOnShiftTab}
  />
  <div class="input-select-items" class:is-open={isOpen}>
    <ul>
      {#if filteredItems.length === 0}
        <li class="disabled" on:click|stopPropagation>Nic nenalezeno</li>
      {/if}
      {#each filteredItems as item, index}
        <li
          class:selected={isSelected(item)}
          class:disabled={item.disabled}
          tabindex={0}
          on:click|stopPropagation={() => selectItem(item)}
          on:keydown={(e) => itemKeyDown(e, item, index)}
        >
          {item.label}
        </li>
      {/each}
    </ul>
  </div>
  <ul class="input-select-messages">
    {#each errorMessages as errorMessage}
      <li>
        {errorMessage}
      </li>
    {/each}
  </ul>
</div>
