// solidjs/src/components/CInput.tsx
import { getRequired } from "@common/ts/validation/required";
import { RuleType } from "@common/ts/validation/ruleType";
import { ValidationField } from "@common/ts/validation/validateFields";
import { Component, For, createEffect, createSignal } from "solid-js";
import { Dynamic, Show } from "solid-js/web";
import { useValidation, useValidationFields } from "./CForm";

export const CInput: Component<{
  ref?: HTMLInputElement | HTMLTextAreaElement,
  name?: string;
  label?: string;
  state?: "success" | "error";
  required?: boolean;
  value?: string;
  rules?: RuleType[];
  type?: string;
  disabled?: boolean;
  autocomplete?: boolean;
  validationMode?: "lazy" | "eager";

  updateValue?: (value: string) => void,
}> = (props) => {
  let innerRef: HTMLInputElement | HTMLTextAreaElement | undefined = undefined;

  const [innerValue, setInnerValue] = createSignal(props.value ?? "");
  const [errorMessages, setErrorMessages] = createSignal<string[]>([]);

  const [height, setHeight] = createSignal("auto");

  const field: ValidationField = {
    getValue: innerValue,
    rules: (props.required ? [getRequired()] : []).concat(props.rules ?? []),
    setMessage: (messages) => setErrorMessages([...messages]),
  };

  const registerField = useValidationFields();
  const validationStatus = useValidation();

  registerField?.register(field);

  createEffect(() => {
    if (props.value !== undefined) {
      setInnerValue(props.value);
    }
  });

  createEffect(() => {
    innerValue()
    if (props.type === "textarea") {
      setHeight("5px");
      setHeight((innerRef?.scrollHeight ?? 0) + 2 + "px");
    }
  });

  const currentState = () => {
    if (errorMessages().length) return "error";
    if (validationStatus?.submitTried()) return "success";

    return props.state;
  };

  const updateInput = (event: Event) => {
    if (props.disabled) return;
    const target = event.target as HTMLInputElement;

    props.updateValue?.(target.value);
    setInnerValue(target.value);

    if (errorMessages().length || props.validationMode === "eager")
      registerField?.revalidate();
  };

  return (
    <div
      class="input-with-label"
      classList={{
        [`input__state-${currentState()}`]: !!currentState(),
      }}
    >
      <Show when={props.label}>
        <label class="label">{props.label}</label>
      </Show>
      <Dynamic
        ref={(ref: HTMLInputElement | HTMLTextAreaElement) => { props.ref = ref; innerRef = ref; }}
        style={`height: ${height()}`}
        component={props.type === 'textarea' ? 'textarea' : 'input'}
        value={innerValue()}
        name={props.name}
        type={props.type}
        class="input"
        disabled={props.disabled}
        placeholder=" "
        autocomplete={props.autocomplete ? 'on' : 'off'}
        onInput={updateInput}
      />
      <ul class="input-messages">
        <For each={errorMessages()}>
          {(errorMessage) => <li>{errorMessage}</li>}
        </For>
      </ul>
    </div>
  )
}

export default CInput;

// svelte/src/components/CInput.svelte
<script lang="ts">
  import { getRequired } from "@common/ts/validation/required";
  import type { RuleType } from "@common/ts/validation/ruleType";
  import {
    type ValidationField,
    validationFieldsKey,
    validationStateKey,
  } from "@common/ts/validation/validateFields";
  import { getContext } from "svelte";
  import { tick } from "svelte";
  import type { Writable } from "svelte/store";

  export let name: string;
  export let label: string;
  export let state: "success" | "error" = null;
  export let required: boolean = false;
  export let value: string = "";
  export let rules: RuleType[] = [];
  export let type: string = "input";
  export let disabled: boolean = false;
  export let autocomplete: boolean = false;
  export let validationMode: "lazy" | "eager" = "lazy";

  let element: HTMLInputElement | HTMLTextAreaElement;
  let innerValue = value ?? "";
  let errorMessages: string[] = [];

  let style = {
    height: "auto",
  };

  const field: ValidationField = {
    getValue: () => innerValue,
    rules: (required ? [getRequired()] : []).concat(rules ?? []),
    setMessage: (messages) => (errorMessages = messages),
  };

  const registerField = getContext<{
    register: (field: ValidationField) => void;
    revalidate: () => void;
  }>(validationFieldsKey);
  registerField?.register(field);

  const { submitTried } =
    getContext<
      | {
          submitTried: Writable<boolean>;
        }
      | undefined
    >(validationStateKey) ?? {};

  $: {
    if (value !== undefined) {
      innerValue = value;
    }
  }

  const updateInput = (event: Event) => {
    if (disabled) return;
    const target = event.target as HTMLInputElement;

    value = target.value;
    innerValue = target.value;

    if (errorMessages.length || validationMode === "eager")
      registerField?.revalidate();
  };

  $: {
    value;
    (async () => {
      await tick();
      if (type === "textarea") {
        style.height = "5px";
        style.height = (element?.scrollHeight ?? 0) + 2 + "px";
      }
    })();
  }

  $: currentState = errorMessages.length
    ? "error"
    : $submitTried
    ? "success"
    : state;

  const select = () => {
    element?.select();
  };

  export const cursorToStart = () => {
    element?.focus();
    element?.setSelectionRange(0, 0);
  };
</script>

<div
  class={`input-with-label ${
    currentState ? `input__state-${currentState}` : ""
  }`}
>
  {#if label}
    <label class="label">{label}</label>
  {/if}
  <svelte:element
    this={type === "textarea" ? "textarea" : "input"}
    bind:this={element}
    style:height={style.height}
    value={innerValue}
    {name}
    {type}
    class="input"
    {disabled}
    placeholder=" "
    autocomplete={autocomplete ? "on" : "off"}
    on:input={updateInput}
  />
  <ul class="input-messages">
    {#each errorMessages as errorMessage}
      <li>
        {errorMessage}
      </li>
    {/each}
  </ul>
</div>
