// solidjs/src/components/CMessageDetail.tsx

import CCard from "@c/CCard";
import { Message } from "@common/ts/api/message";
import { Component } from "solid-js";

const CMessageDetail: Component<{
  message: Message
}> = (props) => {

  const from = () => props.message.message_content?.user?.nickname;
  const subject = () => props.message.message_content?.subject;
  const content = () => props.message.message_content?.content;
  const to = () => props.message.message_content?.recipients
    ?.map((item) => item.nickname)
    .join(", ")


  return (
    <CCard title="Detail zprávy">
      <div class="message-detail">
        <span>Od: {from}</span>
        <span>Pro: {to}</span>
        <span>Předmět: {subject}</span>
        <span style="white-space: pre-line">
          Obsah:<br />
          {content}
        </span>
      </div>
    </CCard>
  )
}

export default CMessageDetail;

// svelte/src/components/CMessageDetail.svelte
<script lang="ts">
  import CCard from "@c/CCard.svelte";
  import type { Message } from "@common/ts/api/message";

  export let message: Message;

  $: from = message.message_content?.user?.nickname;
  const subject = message.message_content?.subject;
  const content = message.message_content?.content;
  const to = message.message_content?.recipients
    ?.map((item) => item.nickname)
    .join(", ");
</script>

<CCard title="Detail zprávy">
  <div class="message-detail">
    <span>Od: {from}</span>
    <span>Pro: {to}</span>
    <span>Předmět: {subject}</span>
    <span style="white-space: pre-line">
      Obsah:<br />
      {content}
    </span>
  </div>
</CCard>
