// vue/src/components/CMessages.vue
<script setup lang="ts">
import { hideMessage, messageQueue } from "@/utils/messages";
import CCard from "./CCard.vue";

defineProps<{ title?: string }>();
</script>

<template>
  <teleport to="body">
    <section class="message-area">
      <c-card
        v-for="(message, index) in messageQueue"
        :title="message.title"
        :color="message.type"
        class="message"
        closable
        @close="() => hideMessage(index)"
      >
        {{ message.content }}
      </c-card>
    </section>
  </teleport>
</template>

// svelte/src/components/CMessages.svelte
<script lang="ts">
  import { hideMessage, messageQueue } from "@/utils/messages";
  import CCard from "./CCard.svelte";
  import CPortal from "./CPortal.svelte";

  export const title: string = "";
</script>

<CPortal>
  <section class="message-area">
    {#each $messageQueue as message, index}
      <CCard
        title={message.title}
        color={message.type}
        class="message"
        closable
        on:close={() => hideMessage(index)}
      >
        {message.content}
      </CCard>
    {/each}
  </section>
</CPortal>
