// solidjs/src/components/CRecipientSelect.tsx
import CInputSelect from "./CInputSelect";
import { getRecipients } from "@common/ts/api/getRecipients";
import { SelectItem } from "@common/ts/api/select";
import { RuleType } from "@common/ts/validation/ruleType";
import { Component, createSignal, onMount } from "solid-js";

const CRecipientSelect: Component<{
  name?: string;
  label?: string;
  state?: "success" | "error";
  required?: boolean;
  disabled?: boolean;
  value?: (string | number)[] | string | number;
  updateValue?: (value: (string | number)[] | string | number) => void;
  rules?: RuleType[];
}> = (props) => {
  const [items, setItems] = createSignal<SelectItem[]>([
    { label: "Načítám", value: null, disabled: true },
  ]);

  onMount(async () => {
    const response = await getRecipients();

    if (response) {
      setItems(response.items);
    }
  });

  return <CInputSelect {...props} multiple items={items()} />
}

export default CRecipientSelect;

// svelte/src/components/CRecipientSelect.svelte
<script lang="ts">
  import CInputSelect from "./CInputSelect.svelte";
  import { getRecipients } from "@common/ts/api/getRecipients";
  import type { SelectItem } from "@common/ts/api/select";
  import { onMount } from "svelte";

  export let name: string;
  export let label: string;
  export let value: (string | number)[] | string | number;
  export let required: boolean;
  export let disabled: boolean;
  let items: SelectItem[] = [{ label: "Načítám", value: null, disabled: true }];

  onMount(async () => {
    const response = await getRecipients();

    if (response) {
      items = response.items;
    }
  });
</script>

<CInputSelect
  multiple
  {items}
  {name}
  {label}
  {required}
  {disabled}
  bind:value
/>
