// vue/src/pages/Login.vue
<script setup lang="ts">
import CForm from "@/components/CForm.vue";
import CCard from "@/components/CCard.vue";
import CInput from "@/components/CInput.vue";
import CLink from "@/components/CLink.vue";
import CButton from "@/components/CButton.vue";
import { ref } from "vue";
import { login, LoginPayload } from "@common/ts/api/login";
import { useRouter } from "vue-router";
import { useStore } from "@/utils/store";

const form = ref<LoginPayload>({
  nickname: "",
  password: "",
  device_name: "vue",
});

const store = useStore();
const router = useRouter();

const submit = async () => {
  const response = await login(form.value);

  if (response) {
    store.isLoggedIn.value = true;
    router.push({ name: "home" });
  }
};
</script>

<template>
  <c-card title="Přihlášení do systému Thessenger">
    <c-form :submit="submit">
      <div class="login-form">
        <c-input
          v-model:value="form.nickname"
          required
          label="Přezdívka"
          name="nickname"
        />
        <c-input
          v-model:value="form.password"
          required
          label="Heslo"
          name="password"
          type="password"
        />
      </div>

      <div class="login-submit-wrapper">
        <c-link :to="{ name: 'register' }">
          Nemáte ještě účet? Registrujte se!
        </c-link>
        <c-button color="success" class="login-submit">Přihlásit se</c-button>
      </div>
    </c-form>
  </c-card>
</template>

// solidjs/src/pages/Login.tsx
import CForm from "@/components/CForm";
import CCard from "@/components/CCard";
import CInput from "@/components/CInput";
import CLink from "@/components/CLink";
import CButton from "@/components/CButton";
import CGuestLayout from "@/components/CGuestLayout";
import { login } from "@common/ts/api/login";
import { useStore } from "@/utils/store";
import { Component, createSignal } from "solid-js";
import { useNavigate } from "@solidjs/router";


const Login: Component = () => {
  const [nickname, setNickname] = createSignal('');
  const [password, setPassword] = createSignal('');


  const store = useStore();
  const navigate = useNavigate();

  const submit = async () => {
    const response = await login({
      device_name: 'solid',
      nickname: nickname(),
      password: password()
    });

    if (response) {
      store.setIsLoggedIn(true);
      navigate('/new-message');
    }
  };

  return (
    <CGuestLayout>
      <CCard title="Přihlášení do systému Thessenger">
        <CForm submit={submit}>
          <div class="login-form">
            <CInput
              value={nickname()}
              updateValue={setNickname}
              required
              label="Přezdívka"
              name="nickname"
            />
            <CInput
              value={password()}
              updateValue={setPassword}
              required
              label="Heslo"
              name="password"
              type="password"
            />
          </div>

          <div class="login-submit-wrapper">
            <CLink to={'/register'}>
              Nemáte ještě účet? Registrujte se!
            </CLink>
            <CButton color="success" class="login-submit">Přihlásit se</CButton>
          </div>
        </CForm>
      </CCard>
    </CGuestLayout>
  )
}

export default Login;
