// svelte/src/pages/Outbox.svelte
<script lang="ts">
  import CMessageList from "@/components/CMessageList.svelte";
  import CCard from "@/components/CCard.svelte";
  import type { Message } from "@common/ts/api/message";
  import { getSentMessages } from "@common/ts/api/getSentMessages";
  import { onMount } from "svelte";
  import type { RouteProps } from "svelte-router-spa/types/components/route";
  import { ignoreUnusedRouteInfo } from "@/utils/router";

  export let params: RouteProps["params"];
  export let currentRoute: RouteProps["currentRoute"];

  ignoreUnusedRouteInfo(currentRoute, params);

  let messages: Message[] = [];

  const showUser = (message: Message): string =>
    message.message_content?.recipients
      ?.map((user) => user.nickname)
      .join(", ") ?? "";

  onMount(async () => {
    const response = await getSentMessages();

    if (response) {
      messages = response.messages;
    }
  });

  const onDeleted = (messageId: string | number) => {
    messages = messages.filter((message) => message.id !== messageId);
  };
</script>

<CCard title="Seznam odeslaných zpráv">
  <CMessageList {messages} {showUser} {onDeleted} />
</CCard>

// solidjs/src/pages/Outbox.tsx

import CMessageList from "@/components/CMessageList";
import CCard from "@/components/CCard";
import { Message } from "@common/ts/api/message";
import { getSentMessages } from "@common/ts/api/getSentMessages";
import { Component, createSignal, onMount } from "solid-js";
import CAppLayout from "@c/CAppLayout";

const Outbox: Component = () => {
  const [messages, setMessages] = createSignal<Message[]>([]);

  const showUser = (message: Message): string =>
    message.message_content?.recipients
      ?.map((user) => user.nickname)
      .join(", ") ?? "";

  onMount(async () => {
    const response = await getSentMessages();

    if (response) {
      setMessages(response.messages);
    }
  });

  const onDeleted = (messageId: string | number) => {
    setMessages(prev => prev.filter((message) => message.id !== messageId));
  };

  return (
    <CAppLayout>
      <CCard title="Seznam odeslaných zpráv">
        <CMessageList
          messages={messages()}
          showUser={showUser}
          onDeleted={onDeleted}
        />
      </CCard>
    </CAppLayout>
  )
}

export default Outbox;
