// solidjs/src/pages/MessageDetail.tsx
import { useStore } from "@/utils/store";
import CAppLayout from "@c/CAppLayout";
import CMessageDetail from "@c/CMessageDetail";
import { getMessage } from "@common/ts/api/getMessage";
import { Message } from "@common/ts/api/message";
import { useParams } from "@solidjs/router";
import { Component, Show, createSignal, onMount } from "solid-js";

const MessageDetail: Component = () => {
  const params = useParams();

  const [message, setMessage] = createSignal<Message>();

  const store = useStore();

  onMount(async () => {
    const response = await getMessage(params.messageId);

    if (response) {
      setMessage(response.message);
      store.setMenuNewMessages(response.numberOfNewMessages);
    }
  });

  return (
    <CAppLayout>
      <Show when={message()} keyed>
        {(value: Message) => <CMessageDetail message={value} />}
      </Show>
    </CAppLayout>
  );
}

export default MessageDetail;

// vue/src/pages/MessageDetail.vue
<script lang="ts" setup>
import { useStore } from "@/utils/store";
import CMessageDetail from "@c/CMessageDetail.vue";
import { getMessage } from "@common/ts/api/getMessage";
import { Message } from "@common/ts/api/message";
import { ref, onMounted } from "vue";

const props = defineProps<{ messageId: string }>();

const message = ref<Message>();

const store = useStore();

onMounted(async () => {
  const response = await getMessage(props.messageId);

  if (response) {
    message.value = response.message;
    store.menuNewMessages.value = response.numberOfNewMessages;
  }
});
</script>

<template>
  <c-message-detail v-if="message" :message="message" />
</template>
